/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthNaverCallbackRouteImport } from './routes/auth.naver.callback'
import { Route as AuthKakaoCallbackRouteImport } from './routes/auth.kakao.callback'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNaverCallbackRoute = AuthNaverCallbackRouteImport.update({
  id: '/auth/naver/callback',
  path: '/auth/naver/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthKakaoCallbackRoute = AuthKakaoCallbackRouteImport.update({
  id: '/auth/kakao/callback',
  path: '/auth/kakao/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/kakao/callback': typeof AuthKakaoCallbackRoute
  '/auth/naver/callback': typeof AuthNaverCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/kakao/callback': typeof AuthKakaoCallbackRoute
  '/auth/naver/callback': typeof AuthNaverCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/kakao/callback': typeof AuthKakaoCallbackRoute
  '/auth/naver/callback': typeof AuthNaverCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/google/callback'
    | '/auth/kakao/callback'
    | '/auth/naver/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/google/callback'
    | '/auth/kakao/callback'
    | '/auth/naver/callback'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/auth/google/callback'
    | '/auth/kakao/callback'
    | '/auth/naver/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthKakaoCallbackRoute: typeof AuthKakaoCallbackRoute
  AuthNaverCallbackRoute: typeof AuthNaverCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/naver/callback': {
      id: '/auth/naver/callback'
      path: '/auth/naver/callback'
      fullPath: '/auth/naver/callback'
      preLoaderRoute: typeof AuthNaverCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/kakao/callback': {
      id: '/auth/kakao/callback'
      path: '/auth/kakao/callback'
      fullPath: '/auth/kakao/callback'
      preLoaderRoute: typeof AuthKakaoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthKakaoCallbackRoute: AuthKakaoCallbackRoute,
  AuthNaverCallbackRoute: AuthNaverCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
